### ISSUE TITLE
Game doesn't launch

### ISSUE THREAD

**Issue by csansoon** [amazingalek/owml#146]
The game launches when I install OWML for the first time. After this, the game is no longer launching anymore from the Mod Manager app neither from OMWL.Launcher.exe. Everytime I try to open it, a console pops up saying "exception: Access denied to UnityEngine.CoreModule.dll'" and then it closes.
![image](https://user-images.githubusercontent.com/57395395/86516119-56a26100-be1e-11ea-8331-efe1b1aa00fc.png)
The game launches correctly from the default executable, without mods.

**Comment by amazingalek** [comment]
Hi, thanks for reporting this issue.

Some questions:

1. Which version of the game do you have? Please make sure it's 1.0.7.
2. What's the location of OWML?

Some things you can try:

1. Make sure OW/OWML isn't already running.
2. Restore the game files and install OWML again (use the Mod Manager if you like). Restoring/resetting the game files can be done in Steam and Epic.
3. Restart your computer.
4. Right click on the game's folder (D:/Games/Outer Wilds) and click Properties. At the bottom, click "Read-only" so it's **not** selected.
5. Open properties of the game folder again, then in the Security tab click "Edit...", select the Users group, make sure it has "Full control". If you are asked if this applies to sub folders as well, click yes.
6. Repeat pt. 4 and 5. on the OWML folder.

**Comment by amazingalek** [comment]
@csansoon any update?
