### ISSUE TITLE
Running multiple instances of OWML simultaneously isn't possible

### ISSUE THREAD

**Issue by amazingalek** [amazingalek/owml#150]

**Comment by amazingalek** [comment]
@Raicuparta you had some thoughts about this? :)

**Comment by Raicuparta** [comment]
I was under the impression that the only thing keeping multiple instances of OWML from running was the fact that they both try to access the same files for logging. So we'd need to prepare for those errors, and maybe just not log stuff to a file on the second instance in case of it being inaccessible? 🤷‍♀️ Could be something else that I didn't notice, though.
