### ISSUE TITLE
Having a mod installed without its dependency crashes OWML without error message

### ISSUE THREAD

**Issue by amazingalek** [amazingalek/owml#193]
To reproduce: install either FreeCam or ObjectSpawner, without having MN-InputHandler istalled and enabled.

OWML crashes without error message:
![image](https://user-images.githubusercontent.com/3322367/87294273-c8a43580-c503-11ea-84ae-80fe1ae71ac0.png)

This happens even if FreeCam/ObjectSpawner is disabled.

Disabling MN-InputHandler will make things run and show relevant error messages:
![image](https://user-images.githubusercontent.com/3322367/87294208-ab6f6700-c503-11ea-8458-218995eee949.png)

**Comment by amazingalek** [comment]
I suggest these changes:

1. Only require dependencies to be installed (and enabled) for enabled mods.
2. When checking for dependencies, check if they're installed, not just enabled.

**Comment by TAImatem** [comment]
fixed
