### ISSUE TITLE
Having duplicate mods crashes OWML and breaks the options menu

### ISSUE THREAD

**Issue by misternebula** [amazingalek/owml#198]
Issue occurred when using post-build events for QSB, so this should only happen to modders. Having two mods with the same unique name crashes OWML with the error :
```
[OWML]: Unity log message: ArgumentException: An element with the same key already exists in the dictionary.. Stack tra
ce: System.Collections.Generic.Dictionary`2[System.String,OWML.Common.IModData].Add (System.String key, IModData value)

OWML.ModLoader.ModSorter.SortMods (IList`1 mods)
OWML.ModLoader.Owo.LoadMods ()
OWML.ModLoader.ModLoader.LoadMods ()
PermanentManager.Awake ()
```
After loading the title screen, the options button does nothing. However, going into the change profile menu and going back loads the option menu fine, but the leave button does nothing.

**Comment by misternebula** [comment]
This bug is in my mod sorter, assigning self.

**Comment by Raicuparta** [comment]
I faced this before, so this is rrlated: https://github.com/Raicuparta/ow-mod-manager/issues/48

OWML should be graceful about it, and OWMM should warn about it.

**Comment by TAImatem** [comment]
fixed
