### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Levi777L** [amazingalek/owml#336]
Does this method work for any unity game?  I have been looking into how to mod VR into Unity games and found a repo for VRGIN and it works for most games but not all.  Trying to get it working on newer games like this one.  Im thinking I just need to redo what they did to use OpenVR like you seem to be doing..... Only a couple days into it tho... =P  Pretty much trying to put my camera controls into any unity game to look around =P  store.steampowered.com/app/602630 (if you want to try out my controls its a free app.  Players didn't seem to like them, but i didn't put in a tutorial. )

**Comment by misternebula** [comment]
Please refrain from self-promotion, and only submit issues with OWML to this section. Any questions can be directed to the modding channel in the Outer Wilds Discord server.

OWML will not work for every game, only Outer Wilds.
