### ISSUE TITLE
Can't get owml and nomaivr to work anymore

### ISSUE THREAD

**Issue by mamefan** [amazingalek/owml#415]
Here are screenshots of the issues and versions. Been trying from within the mod manager and with the owml launcher exe by itself. Haven't tried reinstalling the game yet. This wasn't an issue until hours into echoes of the eye. Tried launch game exe directly. This is the steam version. Tried moving the game to the C drive but no change.

![vlcsnap-2021-12-21-20h27m21s626 (3)](https://user-images.githubusercontent.com/23621179/147019986-a58ce4c7-3fe2-4dce-b632-f7f0530b06fa.jpg)
![ow1](https://user-images.githubusercontent.com/23621179/147019988-e00ec594-3537-4a51-93b2-b25648fe62ca.PNG)
![ow3](https://user-images.githubusercontent.com/23621179/147019989-b03d94ac-c07d-40cf-8e57-5af8ab569cfe.PNG)
![ow4](https://user-images.githubusercontent.com/23621179/147019990-1605d62e-a053-46d6-a5bb-834d2f741f02.PNG)
.

**Comment by TAImatem** [comment]
Have you tried restoring your game files (verify integrity) after the update?

**Comment by mamefan** [comment]
Yes, multiple times. Also tried uninstalling and reinstalling mod manager
and nomaivr.

**Comment by mamefan** [comment]
This fixed it:

Can you please download the latest version of OWML from here
https://github.com/amazingalek/owml/releases/download/2.2.0/OWML.zip and
override all the files in your OWML dir?
I think the OWML.Common.dll for some reason is from a previous version of
OWML
