### ISSUE TITLE
Unity 5 asset errors in console

### ISSUE THREAD

**Issue by dpraul** [amazingalek/owml#416]
Not sure if this is actually an issue since the game ran fine, but I had errors similar to the following from OMWL in the logs after I had finished playing:

> Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_01/Center_01_HighResCol", Mesh asset path "" Mesh name "Center_01_HighResCol"

Running Windows 10 with EOTE DLC installed. Full logs are included below:

<details><summary>Mod Manager Logs</summary>

Log message | Message source |  
-- | -- | --
Started console server on port 59322 | Mod Manager |  
Client connected to console | Mod Manager |  
Started OWML v2.2.0 | OWML |  
Game found in C:/Program Files (x86)/Steam/steamapps/common/Outer Wilds | OWML |  
Game version: 1.1.12.125 | OWML |  
Potentially unsupported game version found, continue at your own risk | OWML |  
Game files copied. | OWML |  
Found mods: | OWML |  
Raicuparta.NomaiVR v2.5.1 | OWML |  
Copying OWML files... | OWML |  
Copying replacement OW files... | OWML |  
Patching OW assembly... | OWML |  
Executing patcher for Raicuparta.NomaiVR v2.5.1 | OWML |  
Starting game via Steam... | OWML |  
Client disconnected from console | Mod Manager |  
Client connected to console | Mod Manager |  
Mod loader has been initialized. | OWML |  
Game version: 1.1.12.125 | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_01/Center_01_HighResCol", Mesh asset path "" Mesh name "Center_01_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_02/Center_02_HighResCol", Mesh asset path "" Mesh name "Center_02_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_04/Center_04_HighResCol", Mesh asset path "" Mesh name "Center_04_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_05/Center_05_HighResCol", Mesh asset path "" Mesh name "Center_05_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_06/Center_06_HighResCol", Mesh asset path "" Mesh name "Center_06_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_07/Center_07_HighResCol", Mesh asset path "" Mesh name "Center_07_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_08/Center_08_HighResCol", Mesh asset path "" Mesh name "Center_08_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_09/Center_09_HighResCol", Mesh asset path "" Mesh name "Center_09_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_10/Center_10_HighResCol", Mesh asset path "" Mesh name "Center_10_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_11/Center_11_HighResCol", Mesh asset path "" Mesh name "Center_11_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_12/Center_12_HighResCol", Mesh asset path "" Mesh name "Center_12_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Center_13/Center_13_HighResCol", Mesh asset path "" Mesh name "Center_13_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Upper_01/Upper_01_HighResCol", Mesh asset path "" Mesh name "Upper_01_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Upper_02/Upper_02_HighResCol", Mesh asset path "" Mesh name "Upper_02_HighResCol" | OWML |  
Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported since Unity 5. If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "RingWorld_Body/Sector_RingInterior/Geometry_RingInterior/Dam_Root/Dam_Broken/Structure_IP_BrokenDam/DamPiece_Upper_03/Upper_03_HighResCol", Mesh asset path "" Mesh name "Upper_03_HighResCol" | OWML |  
  | OWML |  
Client disconnected from console
</details>

**Comment by amazingalek** [comment]
That's probably errors/warning from OW which happen anyways, just not normally shown to users. Closing - I'll reopen if I'm wrong :)
