### ISSUE TITLE
How can I get this to work with epic games version of Outer Wilds?

### ISSUE THREAD

**Issue by ShnitzelKiller** [amazingalek/owml#434]
The game does not appear linked in any way to the mod loader. It does not start when I press "start game" in the mod loader, even if I have the EGS running. Can I specify the game path somehow?

**Comment by sandsalamand** [comment]
Did you specify the path to the game folder in the Settings menu?

**Comment by ShnitzelKiller** [comment]
actually I just had to press the download button next to OWML... I assumed that since it was in the "activated" category it was already installed by the mod manager. Weird.
