### ISSUE TITLE
Crash to Desktop: "An existing connection was forcibly closed by the rmeote host..."

### ISSUE THREAD

**Issue by SuperDuperFuntastic** [amazingalek/owml#435]
Crashed to desktop while playing Echoes of the Eye with NomaiVR. Crashed about a minute into a new loop while landing my ship.

Noticed the following logs from OWML.launcher.exe after the crash:

Started OWML v2.3.2
Game found in C:/Program Files (x86)/Steam/steamapps/common/Outer Wilds
Game version: 1.1.12.168
Game version is supported
Game files copied.
Found mods:
* Artum.NomaiVRFoveated v1.0.3
* Raicuparta.NomaiVR v2.6.0
Copying OWML files...
Copying replacement OW files...
Patching OW assembly...
- Assembly is already patched.
Executing patcher for Artum.NomaiVRFoveated v1.0.3
Executing patcher for Raicuparta.NomaiVR v2.6.0
Identified as a Steam install. Launching...
Console connected to socket!
[OWML.Owo] : Mod loader has been initialized.
[OWML.Owo] : Game version: 1.1.12.168
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Start NomaiVRFoveated
[NomaiVR Fixed Foveated Rendering.ModAssets] : Loading asset bundle from C:/.../OWML/Mods\Artum.NomaiVRFoveated\assets/foveated-shaders
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler
[NomaiVR Fixed Foveated Rendering.NomaiVRFoveated] : Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler
Error while listening: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at OWML.Launcher.SocketListener.ListenToSocket() in D:\a\owml\owml\src\OWML.Launcher\SocketListener.cs:line 77
   at OWML.Launcher.SocketListener.SetupSocketListener() in D:\a\owml\owml\src\OWML.Launcher\SocketListener.cs:line 42

**Comment by amazingalek** [comment]
Hi, thanks for the report. Has it happened again?

**Comment by SuperDuperFuntastic** [comment]
> Hi, thanks for the report. Has it happened again?

Thanks for checking in. Unfortunately I haven't had much time to play since I reported the issue, but I'll be able to try again in a few days and provide an update.

**Comment by TAImatem** [comment]
BTW the "connection was forcibly closed" is most probably because of console loosing connection to the game.
And can you check if you have debug logging options enabled before you launch OW next time? Your current logs seem hold too little information to pinpoint the exact problem

**Comment by SuperDuperFuntastic** [comment]
I have not gotten the error again since reporting it. I did end up uninstalling the NomaiVR Fixed Foveated Rendering (1.0.3) mod and then went through the "verify integrity of game files" process via Steam prior to my most recent session. Not sure if that was the root issue or just a happy coincidence, but things seem to be working just fine. Thanks again!
