### ISSUE TITLE
Error in game

### ISSUE THREAD

**Issue by Mostkiller007** [amazingalek/owml#439]
`Cannot set the parent of the GameObject 'Prefab_CloudExit_GD_StatueIsland(Clone)' while activating or deactivating the parent GameObject 'CloudLayer_Fluid'.`
The game crashes in the begining after the statue cutscene.

**Comment by misternebula** [comment]
This is not an OWML-caused issue. If you have any mods installed, contact their devs about this. If not, reinstall OWML and the game.
