### ISSUE TITLE
Loaded audio does not loop

### ISSUE THREAD

**Issue by xen-42** [amazingalek/owml#440]
Seems as if there's just silence added to the end so it never loops within a reasonable amount of time

**Comment by misternebula** [comment]
This is because this line : https://github.com/amazingalek/owml/blob/5c4f6e207fbb156225cadc2e058835251069cff4/src/OWML.ModHelper.Assets/ModAssets.cs#L106
uses `reader.Length`, but AudioClip.Create takes the sample length of the audio clip instead.
